async function run() {
  
}

run().catch(error => console.log(error))